// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package gensqlc

import (
	"time"

	"github.com/google/uuid"
)

type City struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Player struct {
	ID          uuid.UUID `json:"id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	MiddleName  *string   `json:"middle_name"`
	Birthday    time.Time `json:"birthday"`
	Photo       *string   `json:"photo"`
	Height      int32     `json:"height"`
	ImpactLeg   string    `json:"impact_leg"`
	MarketValue int32     `json:"market_value"`
	CityID      uuid.UUID `json:"city_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PlayerPosition struct {
	PlayerID   uuid.UUID `json:"player_id"`
	PositionID uuid.UUID `json:"position_id"`
	Main       bool      `json:"main"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Position struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
